id: hl7.fhir.us.pq-cmc-fda
canonical: http://hl7.org/fhir/us/pq-cmc-fda 
name: FHIR_pqcmc_fda
title: "Pharmaceutical Quality - Chemistry, Manufacturing and Controls (PQ-CMC) Submissions to FDA"
description: "The FDA PQ-CMC FHIR IG  is for submission of structured and standardized information regarding drug product quality, chemistry, manufacturing and processes controls.  This data is intended for submission to the US FDA by biopharmaceutical companies for the purpose of drug application review."

status: active
license: CC0-1.0 #https://www.hl7.org/fhir/valueset-spdx-license.html
version: 1.0.0-ballot
fhirVersion: 5.0.0
copyrightYear: 2021+
releaseLabel: STU 1-ballot

extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg  
    valueCode: brr
publisher:
  name: HL7 International / Biomedical Research and Regulation 
  url:  'http://www.hl7.org/Special/committees/rcrim' 
  email: brr@lists.HL7.org
jurisdiction: urn:iso:std:iso:3166#US "United States of America"

dependencies:  
  hl7.terminology: 5.5.0

menu:
  Table of Contents: toc.html
  Home: index.html
  General Instructions: instruction.html
  eCTD Profiles (Stage 1):
    Description and Composition of the Drug Product (3.2.P.1): eCTD32P10.html 
    General Information (3.2.S.1): eCTD32S10.html 
    Control of Materials (3.2.S.2.3): eCTD32S23.html
    Specification (3.2.S.4.1, 3.2.P.4 & 3.2.P.5.1): eCTDSP4151.html 
#  DRAFT eCTD Profiles:
#    Product Batch Formula (3.2.P.3.2): eCTD32P32.html 
#    Product Characterization of Impurities (3.2.P.5.5): eCTD32P55.html 
#    Product Container Closure System (3.2.P.7.0): eCTD32P70.html 
#    Substance Characterization (3.2.S.3.0): eCTD32S30.html 
#    Substance Container Closure System (3.2.S.6.0): eCTD32S60.html
#    Batch Analyses (3.2.S.4.4 & 3.2.P.5.4): eCTDSP4454.html 
#    Stability Summary (3.2.S.7.1 & 3.2.P.8.1): eCTDSP7181.html
#    Stability Data (3.2.S.7.3 & 3.2.P.8.3): eCTDSP7383.html
  Artifacts: artifacts.html
  Downloads: downloads.html
  Change Notes: change_notes.html

pages:
  index.html:
    title: "Home"
    generation: markdown
  instruction.html:
    title: "General Instructions"
    generation: markdown
  eCTD32P10.html:
    title: "Description and Composition of the Drug Product (3.2.P.1)"
    generation: markdown
  eCTD32S10.html:
    title: "General Information (3.2.S.1)"
    generation: markdown
  eCTD32S23.html:
    title: "Substance Control of Materials (3.2.S.2.3)"
    generation: markdown
  eCTDSP4151.html:
    title: "Specification (3.2.S.4.1, 3.2.P.4 and 3.2.P.5.1)"
    generation: markdown
  artifacts.html:
    title: "Artifact List"
  downloads.html:
    title: "Downloads"
    generation: markdown
  change_notes.html:
    title: "Change Notes"
    generation: markdown


parameters:
 releaselabel: true
 excludettl: true
 excludemap: true
 apply-wg: true
 jira-code: pq-cmc
 # {joint-iso-itu-t(2) country(16) us(840) organization(1) hl7(113883)}
 auto-oid-root: 2.16.840.1.113883.4.642.40.36
 special-url: http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl
    - https://www.uniprot.org
    - urn:oid:1.3.6.1.4.1.5193
    - http://unitsofmeasure.org
    - urn:oid:1.3.6.1.4.1.519.1
    - urn:oid:2.16.840.1.113883.4.82
    - https://www.fda.gov/drugs/drug-approvals-and-databases/drug-establishments-current-registration-site
    - urn:ietf:rfc:3986
#   validation: [allow-any-extensions, no-broken-links]




